/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TiendaRouteImport } from './routes/tienda'
import { Route as SobreNosotrosRouteImport } from './routes/sobre-nosotros'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as IndexRouteImport } from './routes/index'

const TiendaRoute = TiendaRouteImport.update({
  id: '/tienda',
  path: '/tienda',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreNosotrosRoute = SobreNosotrosRouteImport.update({
  id: '/sobre-nosotros',
  path: '/sobre-nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/tienda': typeof TiendaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/tienda': typeof TiendaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/tienda': typeof TiendaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contacto' | '/sobre-nosotros' | '/tienda'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contacto' | '/sobre-nosotros' | '/tienda'
  id: '__root__' | '/' | '/contacto' | '/sobre-nosotros' | '/tienda'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactoRoute: typeof ContactoRoute
  SobreNosotrosRoute: typeof SobreNosotrosRoute
  TiendaRoute: typeof TiendaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tienda': {
      id: '/tienda'
      path: '/tienda'
      fullPath: '/tienda'
      preLoaderRoute: typeof TiendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre-nosotros': {
      id: '/sobre-nosotros'
      path: '/sobre-nosotros'
      fullPath: '/sobre-nosotros'
      preLoaderRoute: typeof SobreNosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactoRoute: ContactoRoute,
  SobreNosotrosRoute: SobreNosotrosRoute,
  TiendaRoute: TiendaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
